baseURL = 'https://colbdavis.github.io/blog'
languageCode = 'en-us'
title = 'My Tech & Life Blog'
theme = 'PaperMod'

[params]
    defaultContentLanguage = "en"
    displayFullLangName = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # This allows HTML inside your Markdown files
